// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo71ODE75q2STI0UyJX3bxHKsqleckd5M',
    appId: '1:521789266315:web:bd1e4e30bc2f2804ba778e',
    messagingSenderId: '521789266315',
    projectId: 'prjpab2-si6b-2226240027',
    authDomain: 'prjpab2-si6b-2226240027.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6b-2226240027-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6b-2226240027.firebasestorage.app',
    measurementId: 'G-FQTDJ4CJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPUnC4fOtc8qMJWwy2-PxMlVzKOufvQg',
    appId: '1:521789266315:android:a61980d361d053d1ba778e',
    messagingSenderId: '521789266315',
    projectId: 'prjpab2-si6b-2226240027',
    databaseURL: 'https://prjpab2-si6b-2226240027-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6b-2226240027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzRSMXPfpygONxRAE0d8VWnvuudfkV27Y',
    appId: '1:521789266315:ios:d1de47c3c0e8dc01ba778e',
    messagingSenderId: '521789266315',
    projectId: 'prjpab2-si6b-2226240027',
    databaseURL: 'https://prjpab2-si6b-2226240027-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6b-2226240027.firebasestorage.app',
    iosClientId: '521789266315-vt1oj9c6bmb74tusi7igi51des9iklqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasNelsen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzRSMXPfpygONxRAE0d8VWnvuudfkV27Y',
    appId: '1:521789266315:ios:d1de47c3c0e8dc01ba778e',
    messagingSenderId: '521789266315',
    projectId: 'prjpab2-si6b-2226240027',
    databaseURL: 'https://prjpab2-si6b-2226240027-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6b-2226240027.firebasestorage.app',
    iosClientId: '521789266315-vt1oj9c6bmb74tusi7igi51des9iklqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasNelsen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo71ODE75q2STI0UyJX3bxHKsqleckd5M',
    appId: '1:521789266315:web:5b7cbc5250aa65f7ba778e',
    messagingSenderId: '521789266315',
    projectId: 'prjpab2-si6b-2226240027',
    authDomain: 'prjpab2-si6b-2226240027.firebaseapp.com',
    databaseURL: 'https://prjpab2-si6b-2226240027-default-rtdb.firebaseio.com',
    storageBucket: 'prjpab2-si6b-2226240027.firebasestorage.app',
    measurementId: 'G-F9L8NREVN6',
  );
}
